refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console

root:
  level: info
  appenders:
    - stdout
loggers:
#  patina::broker:
#    level: info
  patina::broker::handler::publish_handler:
    level: error
  patina::broker::handler::connect_handler:
    level: error
  patina::broker::handler::subscribe_handler:
    level: error
#  patina::connection:
#    level: info
#  patina::metrics:
#    level: info
#  patina::serdes:
#    level: error
#  patina::session:
#    level: info
#  patina::tests:
#    level: info
#  patina::topic:
#    level: info
  mio::poll:
    level: info
  hyper:
    level: warn
  tracing:
    level: warn
  warp:
    level: warn