refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console

root:
  level: trace
  appenders:
    - stdout
loggers:
  mqtt::session:
    level: warn
  mqtt::broker:
    level: trace
  mqtt::connection_handler:
    level: warn
  mqtt::connection:
    level: info
  mqtt::decoder:
    level: warn
  mqtt::encoder:
    level: warn
  mqtt::topic_handler:
    level: trace
  mio::poll:
    level: info
