refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console

root:
  level: info
  appenders:
    - stdout
loggers:
  patina::broker:
    level: info
  patina::connection:
    level: info
  patina::metrics:
    level: info
  patina::serdes:
    level: info
  patina::session:
    level: info
  patina::tests:
    level: info
  patina::topic:
    level: info
  mio::poll:
    level: info
  hyper:
    level: warn
  tracing:
    level: warn
  warp:
    level: warn